package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 12 novembre 2025 22 h 23 GMT+01:00
*/

public interface IBanqueRemoteOperations 
{
  void creerCompte (Compte cpte);
  void verser (float mt, int code);
  void retirer (float mt, int code);
  Compte getCompte (int code);
  Compte[] getComptes ();
  double conversion (float mt);
} // interface IBanqueRemoteOperations
