package corbaBanque;


/**
* corbaBanque/tabComptesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 12 novembre 2025 22 h 23 GMT+01:00
*/

public final class tabComptesHolder implements org.omg.CORBA.portable.Streamable
{
  public Compte value[] = null;

  public tabComptesHolder ()
  {
  }

  public tabComptesHolder (Compte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tabComptesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tabComptesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tabComptesHelper.type ();
  }

}
